# Generated by Django 3.2.2 on 2021-10-20 21:23

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='banner',
            field=models.ImageField(default='users/user_default_bg.jpg', upload_to=accounts.models.user_directory_path_banner),
        ),
    ]
