# Generated by Django 3.2.2 on 2021-10-22 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20211022_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='share_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
