# Generated by Django 3.2.2 on 2021-10-22 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_socialpost_share_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialpost',
            old_name='share_on',
            new_name='shared_on',
        ),
    ]
