# Generated by Django 3.2.2 on 2021-10-21 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_rename_dislike_socialcomment_dislikes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialcomment',
            old_name='commet',
            new_name='comment',
        ),
    ]
